version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pwd123
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pwd123
        MONGO_INITDB_DATABASE: usersAPI
    ports:
      - "27017:27017"